# module Numpy

## machine learnia_video 10
https://youtu.be/NzDQTrqsxas

In [1]:
import numpy as np

In [9]:
t = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(f"{t} est de type {type(t)}")
print(f"{t} est de dimension {t.ndim}, de forme {t.shape}, de taille {t.size}")

[[1 2 3 4]
 [5 6 7 8]] est de type <class 'numpy.ndarray'>
[[1 2 3 4]
 [5 6 7 8]] est de dimension 2, de forme (2, 4), de taille 8


In [11]:
t_0 = np.zeros((3,4))   # attention shape est un tuple
print(t_0)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [12]:
t_1 = np.ones((3,4))   # attention shape est un tuple
print(t_1)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [16]:
t_valeur = np.full((4,3),2)   # attention shape est un tuple
print(t_valeur)

[[2 2 2]
 [2 2 2]
 [2 2 2]
 [2 2 2]]


In [28]:
t_rand = np.random.randn(3,4)   # attention PAS de tuple ici
print(t_rand)

[[ 0.34900258 -1.85851316 -1.16718189  1.42489683]
 [ 1.49656536  1.28993206 -1.81174527 -1.49830721]
 [-1.45014322 -1.69390696  0.22726403 -0.48973471]]


In [26]:
np.random.seed(15)              # variantes : si on choisit la seed, les nombres restent identiques (en relançant)
t_rand_fixe = np.random.randn(3,4)   # attention PAS de tuple ici
print(t_rand_fixe)

[[-0.31232848  0.33928471 -0.15590853 -0.50178967]
 [ 0.23556889 -1.76360526 -1.09586204 -1.08776574]
 [-0.30517005 -0.47374837 -0.20059454  0.35519677]]


In [29]:
t_Id = np.eye(4)
print(t_Id)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [36]:
# utilie pour matplotlib
t_nbe_de_valeur = np.linspace(0, 10, 4)
t_espacement_regulier = np.arange(0,10,3)
print(f"{t_nbe_de_valeur} est de taille {t_nbe_de_valeur.size}")
print(f"{t_espacement_regulier} est de taille {t_espacement_regulier.size}")

[ 0.          3.33333333  6.66666667 10.        ] est de taille 4
[0 3 6 9] est de taille 4


In [39]:
t_1 = np.zeros((4,3))
t_2 = np.ones((3,3))
t = np.concatenate((t_1, t_2), axis = 0)
print(t)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [43]:
t_1 = np.zeros((3,4))
t_2 = np.ones((3,3))
t = np.concatenate((t_1, t_2), axis = 1)
print(t)

[[0. 0. 0. 0. 1. 1. 1.]
 [0. 0. 0. 0. 1. 1. 1.]
 [0. 0. 0. 0. 1. 1. 1.]]


In [59]:
t_1 = [i for i in range(12)]
t_1 = np.reshape(t_1, (3,4,1))
#print(t_1)
t_2 = [i for i in range(12, 24)]
t_2 = np.reshape(t_2, (3,4,1))
#print(t_2)
t = np.concatenate((t_1, t_2), axis = 2)
print(t[1,0])

[ 4 16]


In [66]:
t_1 = np.zeros((3,3))
t_2 = np.ones((3,3))
t = np.concatenate((t_1, t_2), axis = 1)
print(t)
print(" ")
t = np.reshape(t, (2,9))
print(t)

[[0. 0. 0. 1. 1. 1.]
 [0. 0. 0. 1. 1. 1.]
 [0. 0. 0. 1. 1. 1.]]
 
[[0. 0. 0. 1. 1. 1. 0. 0. 0.]
 [1. 1. 1. 0. 0. 0. 1. 1. 1.]]


In [82]:
# utilité de la méthode reshape et squeeze
t = np.array([1, 2, 3, 4])
print(t.shape)
t = t.reshape((t.shape[0],1))
print(t.shape)
t = t.squeeze()
print(t.shape)

(4,)
(4, 1)
(4,)


In [83]:
# utilité de la méthode ravel
t_1 = np.zeros((3,3))
t_2 = np.ones((3,3))
t = np.concatenate((t_1, t_2), axis = 1)
print(t)
print(" ")
t = t.ravel()
print(t)

[[0. 0. 0. 1. 1. 1.]
 [0. 0. 0. 1. 1. 1.]
 [0. 0. 0. 1. 1. 1.]]
 
[0. 0. 0. 1. 1. 1. 0. 0. 0. 1. 1. 1. 0. 0. 0. 1. 1. 1.]
