# module Numpy

machine learnia_video 12 &nbsp; &nbsp; &nbsp; [lien](https://youtu.be/RwFiNlL4Q8g)

In [2]:
import numpy as np

In [17]:
np.random.seed(0)
A = np.random.randint(0, 10, [2, 3])
A

array([[5, 0, 3],
       [3, 7, 9]])

## 1. méthode ndarray &nbsp; &nbsp; &nbsp; [lien](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.html)

In [18]:
print(f"somme = {A.sum()} - moyenne = {A.mean()} - max = {A.max()} - min = {A.min()}")

somme = 27 - moyenne = 4.5 - max = 9 - min = 0


In [14]:
A.sum(axis=0)

array([ 8,  7, 12])

In [15]:
A.sum(axis=1)

array([ 8, 19])

In [23]:
# position du minimum
print(A)
print()
print(A.argmin(axis = 0))
print()
print(A.argmin(axis = 0).argmin(axis = 0))

[[5 0 3]
 [3 7 9]]

[1 0 0]

1


In [41]:
#.sort() et .argsort()
B = np.array([1, 3, -2, 5])
print(B)
print()
C = np.sort(B)
print(C)
print()
D = np.argsort(B)
print(D)

[ 1  3 -2  5]

[-2  1  3  5]

[2 0 1 3]


## 2. fonction mathématique &nbsp; &nbsp; &nbsp; [lien](https://docs.scipy.org/doc/numpy-1.13.0/reference/routines.math.html)

In [49]:
np.random.seed(0)
A = np.random.randint(0, 10, [2, 3])
print(A)
print()
exp_A = np.exp(A)
print(exp_A)

[[5 0 3]
 [3 7 9]]

[[1.48413159e+02 1.00000000e+00 2.00855369e+01]
 [2.00855369e+01 1.09663316e+03 8.10308393e+03]]


## 3. statistique &nbsp; &nbsp; &nbsp; [lien](https://docs.scipy.org/doc/numpy-1.13.0/reference/routines.statistics.html)

In [2]:
A

NameError: name 'A' is not defined

In [52]:
print(f"moyenne = {A.mean()} - variance = {A.var():.3f} - écart type = {A.std():.3f}")

moyenne = 4.5 - variance = 8.583 - écart type = 2.930


In [53]:
# coef de corélation entre les différents lignes
np.corrcoef(A)

array([[ 1.        , -0.56362148],
       [-0.56362148,  1.        ]])

In [55]:
np.unique(A, return_counts=True)

(array([0, 3, 5, 7, 9]), array([1, 2, 1, 1, 1], dtype=int64))

In [5]:
import numpy as np
np.random.seed(0)
A = np.random.randint(0, 10, [5, 5])
print(A)
print()
value, count = np.unique(A, return_counts=True)
print(value)
print()
print(count)
print()
print(count.argsort())

[[5 0 3 3 7]
 [9 3 5 2 4]
 [7 6 8 8 1]
 [6 7 7 8 1]
 [5 9 8 9 4]]

[0 1 2 3 4 5 6 7 8 9]

[1 2 1 3 2 3 2 4 4 3]

[0 2 1 4 6 3 5 9 7 8]


In [9]:
B = value[count.argsort()]
print(B)
C = count[count.argsort()]
print(C)

[0 2 1 4 6 3 5 9 7 8]
[1 1 2 2 2 3 3 3 4 4]


In [10]:
for i,j in zip(value[count.argsort()], count[count.argsort()]):
    print(f"la valeur {i} apparaît {j} fois")

la valeur 0 apparaît 1 fois
la valeur 2 apparaît 1 fois
la valeur 1 apparaît 2 fois
la valeur 4 apparaît 2 fois
la valeur 6 apparaît 2 fois
la valeur 3 apparaît 3 fois
la valeur 5 apparaît 3 fois
la valeur 9 apparaît 3 fois
la valeur 7 apparaît 4 fois
la valeur 8 apparaît 4 fois


## 4. NaN correction

In [14]:
import numpy as np
A = np.random.randn(5, 5)
A[0,2] = np.nan
A[4,3] = np.nan
A

array([[ 1.76405235,  0.40015721,         nan,  2.2408932 ,  1.86755799],
       [-0.97727788,  0.95008842, -0.15135721, -0.10321885,  0.4105985 ],
       [ 0.14404357,  1.45427351,  0.76103773,  0.12167502,  0.44386323],
       [ 0.33367433,  1.49407907, -0.20515826,  0.3130677 , -0.85409574],
       [-2.55298982,  0.6536186 ,  0.8644362 ,         nan,  2.26975462]])

In [15]:
A.mean()

nan

In [22]:
np.nanmean(A)

0.5062075424895804

In [32]:
nb_nan = np.isnan(A).sum()
pc_nan = nb_nan/A.size*100
print(f"il y a {nb_nan} NaN dans notre tableau, ce qui représente {pc_nan:.0f} % des valeurs totales")

il y a 2 NaN dans notre tableau, ce qui représente 8 % des valeurs totales


In [33]:
# boolean indexing = application du masuqe des NaN
A[np.isnan(A)] = 0
A

array([[ 1.76405235,  0.40015721,  0.        ,  2.2408932 ,  1.86755799],
       [-0.97727788,  0.95008842, -0.15135721, -0.10321885,  0.4105985 ],
       [ 0.14404357,  1.45427351,  0.76103773,  0.12167502,  0.44386323],
       [ 0.33367433,  1.49407907, -0.20515826,  0.3130677 , -0.85409574],
       [-2.55298982,  0.6536186 ,  0.8644362 ,  0.        ,  2.26975462]])

## 5. algèbre linéaire &nbsp; &nbsp; &nbsp; [lien](https://docs.scipy.org/doc/numpy-1.13.0/reference/routines.linalg.html)

In [34]:
import numpy as np
A = np.ones((2,3))
B = np.ones((3,2))
print(A)
print()
print(B)

[[1. 1. 1.]
 [1. 1. 1.]]

[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [36]:
A.T    # transposée

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [37]:
A.dot(B)    # produit matriciel AB

array([[3., 3.],
       [3., 3.]])

In [76]:
C = np.random.randint(0,10,[3,3])
print(C)
print()
print(f"det C = {np.linalg.det(C):.3f}")
D = np.linalg.inv(C)               # préciser l'utilisation de np.linalg.pinv(C) = pseudo inverse ... ???
print(C)
print()


C_valeur, C_vecteur = np.linalg.eig(C)
#print("valeurs propres :")
#print(C_valeur)
#print()
#print("vecteurs propres :")
#print(C_vecteur)
#print()

for i in range(len(C_valeur)):
    print(f"vp {C_valeur[i]:.3f} associée au vp {C_vecteur[i]}")

[[8 9 8]
 [3 6 1]
 [7 4 9]]

det C = -20.000
[[8 9 8]
 [3 6 1]
 [7 4 9]]

vp 18.144 associée au vp [-0.72081637 -0.81656543 -0.04918056]
vp -0.217 associée au vp [-0.23184799  0.31635154 -0.65457716]
vp 5.073 associée au vp [-0.65320003  0.48284843  0.7543938 ]


## 6. exercice : standardiser une matrice (centrer er réduire)
( x - moyenne(x) ) / ecart_type

In [47]:
import numpy as np
np.random.seed(0)
A = np.random.randint(0, 100, [10,5])
A

array([[44, 47, 64, 67, 67],
       [ 9, 83, 21, 36, 87],
       [70, 88, 88, 12, 58],
       [65, 39, 87, 46, 88],
       [81, 37, 25, 77, 72],
       [ 9, 20, 80, 69, 79],
       [47, 64, 82, 99, 88],
       [49, 29, 19, 19, 14],
       [39, 32, 65,  9, 57],
       [32, 31, 74, 23, 35]])

In [48]:
B = ( A - A.mean( axis=0 ) ) / A.std( axis=0)
B

array([[-0.02206157,  0.        ,  0.13173823,  0.72539252,  0.10755798],
       [-1.56637126,  1.61579632, -1.48676006, -0.33034307,  0.96802178],
       [ 1.12513992,  1.84021247,  1.03508612, -1.14768676, -0.27965074],
       [ 0.90452425, -0.35906585,  0.99744662,  0.0102168 ,  1.01104497],
       [ 1.6104944 , -0.44883231, -1.33620208,  1.0659524 ,  0.32267393],
       [-1.56637126, -1.21184724,  0.73397016,  0.7935045 ,  0.62383626],
       [ 0.11030784,  0.76301493,  0.80924915,  1.81518411,  1.01104497],
       [ 0.1985541 , -0.80789816, -1.56203905, -0.90929485, -2.17267111],
       [-0.24267724, -0.67324847,  0.16937773, -1.24985473, -0.32267393],
       [-0.55153918, -0.7181317 ,  0.50813319, -0.77307091, -1.26918412]])

<u>vérification</u> : somme des composantes de chaque vecteurs

In [51]:
print(B.mean( axis=0 ))
print(B.std( axis=0 ))

[-2.22044605e-17 -4.44089210e-17  0.00000000e+00 -1.22124533e-16
 -4.44089210e-17]
[1. 1. 1. 1. 1.]
