# module Numpy

## machine learnia_video 13
https://youtu.be/lIESSFHGalA

In [1]:
import numpy as np

In [2]:
np.random.seed(0)
A = np.random.randint(0, 10, [2,3])
B = np.ones([2,3])

In [6]:
A

array([[5, 0, 3],
       [3, 7, 9]])

In [4]:
B

array([[1., 1., 1.],
       [1., 1., 1.]])

In [7]:
C = A + B
C

array([[ 6.,  1.,  4.],
       [ 4.,  8., 10.]])

## broacasting (extention des dimentions)

In [20]:
import numpy as np
np.random.seed(0)
A = np.random.randint(0, 10, [2,3])

In [21]:
A+2

array([[ 7,  2,  5],
       [ 5,  9, 11]])

In [33]:
B = np.ones([2,1])
C = np.ones([1,3])

In [34]:
print(A+B)
print()
print(A+C)

[[ 6.  1.  4.]
 [ 4.  8. 10.]]

[[ 6.  1.  4.]
 [ 4.  8. 10.]]


In [24]:
B = np.ones([2,2])
B

array([[1., 1.],
       [1., 1.]])

In [25]:
A+B

ValueError: operands could not be broadcast together with shapes (2,3) (2,2) 

<u>explication des règles du broacasting :</u>
* soit les dimensions sont égales
* soit les dimensions respectives sont égales à 1

In [35]:
A = np.random.randint(0, 10, [4,1])
B = np.random.randint(0, 10, [1,3])
A+B

array([[10,  9, 11],
       [12, 11, 13],
       [ 9,  8, 10],
       [11, 10, 12]])

<u>conseil :</u> si les dimensions sont incomplètes, penser à les compléter avec la fonctions reshape\
voici un contre-ex dangereux

In [36]:
A = np.random.randint(0, 10, [10,1])
B = np.random.randint(0, 10, [10,1])
B = B.reshape(B.shape[0],)
print(f"shape A= {A.shape} et shape B = {B.shape}")

shape A= (10, 1) et shape B = (10,)


voici le problème : B a été applati ...

In [40]:
print(A-B)
print((A-B).shape)

[[-1  4  5  8  5  3  8  6  5  0]
 [-8 -3 -2  1 -2 -4  1 -1 -2 -7]
 [-3  2  3  6  3  1  6  4  3 -2]
 [-2  3  4  7  4  2  7  5  4 -1]
 [-2  3  4  7  4  2  7  5  4 -1]
 [-1  4  5  8  5  3  8  6  5  0]
 [-8 -3 -2  1 -2 -4  1 -1 -2 -7]
 [-4  1  2  5  2  0  5  3  2 -3]
 [ 0  5  6  9  6  4  9  7  6  1]
 [-1  4  5  8  5  3  8  6  5  0]]
(10, 10)


In [41]:
A = np.random.randint(0, 10, [10,1])
B = np.random.randint(0, 10, [10,1])
print(A-B)
print((A-B).shape)

[[-3]
 [-4]
 [ 0]
 [ 1]
 [ 0]
 [-2]
 [ 1]
 [ 9]
 [ 5]
 [-5]]
(10, 1)
